language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - ./bin/travis/install_phpcs.sh

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration=tests/phpunit.xml
    # php code standards
  - vendor/bin/php-cs-fixer fix -v --dry-run lib
  - vendor/bin/php-cs-fixer fix -v --dry-run tests
  - bin/travis/run_phpcs.sh
  # mess detector
  - vendor/bin/phpcpd lib tests
  # dead code detector
  - vendor/bin/phpdcd lib tests

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3.3
